export const BREADCRUMB_LABELS = {
  "offres-emploi": "Offres d'emploi",
  "mission-management": "Missions",
  "contrat-management": "Contrats",
  "finance-management": "Finance",
  "agent-management": "Gestion agents",
  "client-management": "Gestion clients",
  client: "Client",
  detail: "Detail",
  edit: "Modification",
  notifications: "Notifications",
  settings: "Parametres",
  dashboard: "Tableau de bord",
  management: "Gestion",
  registration: "Ajout",
  evaluation: "Evaluation",
} as const;
