export const ROUTES = {
  dashboard: "/dashboard",
  agentManagement: "/agent-management",
  agentRegistration: "/agent-management/registration",
  agentEvaluation: "/agent-management/evaluation",
  agentDetail: (agentId: string) => `/agent-management/detail/${agentId}`,
  agentEdit: (agentId: string) => `/agent-management/detail/${agentId}/edit`,
  clientManagement: "/client-management",
  clientRegistration: "/client-management/registration",
  clientDetail: (clientId: string) => `/client-management/detail/${clientId}`,
  clientEdit: (clientId: string) => `/client-management/detail/${clientId}/edit`,
  notifications: "/notifications",
  settings: "/settings",
  offresEmploi: "/offres-emploi",
  offreEmploiRegistration: "/offres-emploi/registration",
  offreEmploiDetail: (offreId: string) => `/offres-emploi/detail/${offreId}`,
  offreEmploiEdit: (offreId: string) => `/offres-emploi/detail/${offreId}/edit`,
  missionManagement: "/mission-management",
  missionRegistration: "/mission-management/registration",
  missionDetail: (missionId: string) => `/mission-management/detail/${missionId}`,
  missionEdit: (missionId: string) => `/mission-management/detail/${missionId}/edit`,
} as const;
