export const ROUTES = {
  login: "/login",
  activateAccount: "/activate-account",
  setupPassword: "/setup-password",
  dashboard: "/dashboard",
  agentManagement: "/agent-management",
  agentRegistration: "/agent-management/registration",
  agentEvaluation: "/agent-management/evaluation",
  agentDetail: (agentId: string) => `/agent-management/detail/${agentId}`,
  agentEdit: (agentId: string) => `/agent-management/detail/${agentId}/edit`,
  agentEmployeurContrat: (agentId: string) => `/agent-management/detail/${agentId}/contrat-employeur`,
  clientManagement: "/client-management",
  clientRegistration: "/client-management/registration",
  clientDetail: (clientId: string) => `/client-management/detail/${clientId}`,
  clientEdit: (clientId: string) => `/client-management/detail/${clientId}/edit`,
  notifications: "/notifications",
  notificationDetail: (notificationId: string) => `/notifications/detail/${notificationId}`,
  settings: "/settings",
  offresEmploi: "/offres-emploi",
  offreEmploiRegistration: "/offres-emploi/registration",
  offreEmploiDetail: (offreId: string) => `/offres-emploi/detail/${offreId}`,
  offreEmploiEdit: (offreId: string) => `/offres-emploi/detail/${offreId}/edit`,
  missionManagement: "/mission-management",
  missionRegistration: "/mission-management/registration",
  missionDetail: (missionId: string) => `/mission-management/detail/${missionId}`,
  missionEdit: (missionId: string) => `/mission-management/detail/${missionId}/edit`,
  contratManagement: "/contrat-management",
  contratBundleDetail: (bundleId: string) => `/contrat-management/detail/${bundleId}`,
  financeManagement: "/finance-management",
  financeMouvementNouveau: "/finance-management/nouveau-mouvement",
  incidents: "/incidents",
  incidentOpen: "/incidents/ouvrir",
  incidentDetail: (incidentId: string) => `/incidents/detail/${incidentId}`,
  analytics: "/analytics",
  userManagement: "/user-management",
  userRoles: "/user-management/roles",
  userRegistration: "/user-management/registration",
  userDetail: (userId: string) => `/user-management/detail/${userId}`,
  userEdit: (userId: string) => `/user-management/edit/${userId}`,
  financeForMission: (missionId: string) => `/finance-management?mission=${missionId}`,
  financeMouvementNouveauForMission: (missionId: string) =>
    `/finance-management/nouveau-mouvement?mission=${encodeURIComponent(missionId)}`,
} as const;
